-- ==============================================================================
-- NutriFam - Seed Oficial: Catálogo Biomecânico de Exercícios (73 Exercícios)
-- Execute este script no SQL Editor do seu projeto Supabase
-- (Dashboard do Supabase -> SQL Editor -> New Query -> Colar e clicar em 'Run')
-- ==============================================================================

INSERT INTO public.exercises (
  id,
  name,
  name_en,
  category,
  equipment,
  target_muscle,
  secondary_muscles,
  instructions,
  tips,
  difficulty,
  gif_url,
  thumbnail_url,
  is_custom,
  created_by
) VALUES
  (
    'chest_bench_press_barbell',
    'Supino Reto com Barra',
    'Barbell Bench Press',
    'chest',
    'barbell',
    'Peitoral Maior (Geral)',
    '{"Tríceps Braquial","Deltoide Anterior"}'::text[],
    'Deite-se no banco reto com os pés firmes no chão. Segure a barra um pouco mais largo que os ombros. Desça a barra de forma controlada até tocar suavemente o meio do peito e empurre para cima.',
    'Apoie bem as escápulas no banco e mantenha os pés firmes no chão para base estável.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/barbell-bench-press.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/barbell-bench-press.gif',
    false,
    NULL
  ),
  (
    'chest_incline_bench_press_barbell',
    'Supino Inclinado com Barra',
    'Incline Barbell Bench Press',
    'chest',
    'barbell',
    'Peitoral Superior (Clavicular)',
    '{"Deltoide Anterior","Tríceps"}'::text[],
    'No banco a 30-45 graus, abaixe a barra até a parte superior do peito com controle, mantendo escápulas retraídas.',
    'Banco regulado entre 30° e 45° para foco clavicular sem sobrecarregar a articulação do ombro.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/barbell-incline-bench-press.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/barbell-incline-bench-press.gif',
    false,
    NULL
  ),
  (
    'chest_bench_press_dumbbell',
    'Supino Reto com Halteres',
    'Dumbbell Bench Press',
    'chest',
    'dumbbell',
    'Peitoral Maior',
    '{"Tríceps","Deltoide Anterior"}'::text[],
    'Deite-se com um halter em cada mão. Desça os halteres abrindo o peito até sentir bom alongamento e empurre aproximando-os no topo.',
    'Permite maior amplitude de movimento e trabalho estabilizador independente para cada braço.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-bench-press.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-bench-press.gif',
    false,
    NULL
  ),
  (
    'chest_incline_bench_press_dumbbell',
    'Supino Inclinado com Halteres',
    'Incline Dumbbell Bench Press',
    'chest',
    'dumbbell',
    'Peitoral Superior',
    '{"Deltoide Anterior","Tríceps"}'::text[],
    'Banco a 30-45 graus. Desça os halteres lateralmente com amplitude controlada e empurre convergindo sem bater os pesos.',
    'Desça abrindo os cotovelos a 45-60 graus do tronco para preservar o manguito rotador.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-incline-bench-press.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-incline-bench-press.gif',
    false,
    NULL
  ),
  (
    'chest_decline_press_dumbbell',
    'Supino Declinado com Halteres',
    'Decline Dumbbell Press',
    'chest',
    'dumbbell',
    'Peitoral Inferior',
    '{"Tríceps","Deltoide Anterior"}'::text[],
    'Em banco declinado, posicione as pernas fixas. Empurre os halteres verticalmente focando na contração da porção inferior do peito.',
    'Foco na porção esternal e inferior do peitoral, mantendo o abdômen contraído.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-decline-bench-press.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-decline-bench-press.gif',
    false,
    NULL
  ),
  (
    'chest_dumbbell_fly',
    'Crucifixo Reto com Halteres',
    'Dumbbell Fly',
    'chest',
    'dumbbell',
    'Peitoral Maior (Foco em Alongamento)',
    '{"Deltoide Anterior"}'::text[],
    'Deitado de costas, abra os braços mantendo leve flexão nos cotovelos. Alongue o peitoral e retorne abraçando o ar.',
    'Mantenha os cotovelos levemente flexionados durante todo o movimento sem bater os pesos no topo.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-fly.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-fly.gif',
    false,
    NULL
  ),
  (
    'chest_incline_dumbbell_fly',
    'Crucifixo Inclinado com Halteres',
    'Incline Dumbbell Fly',
    'chest',
    'dumbbell',
    'Peitoral Superior',
    '{"Deltoide Anterior"}'::text[],
    'Em banco a 30-45 graus, abra os braços em arco suave sentindo o alongamento da porção clavicular.',
    'Excelente para alongar as fibras superiores do peitoral com controle de cadência.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-incline-fly.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-incline-fly.gif',
    false,
    NULL
  ),
  (
    'chest_cable_crossover_high',
    'Crossover Polia Alta',
    'High Cable Crossover',
    'chest',
    'cable',
    'Peitoral Inferior e Esterno',
    '{"Deltoide Anterior","Core"}'::text[],
    'Com os cabos na altura máxima, dê um passo à frente e puxe os cabos para baixo e para frente cruzando as mãos levemente.',
    'Incline ligeiramente o tronco e aperte o peitoral por 1 segundo no ponto de pico de contração.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/cable-standing-up-straight-crossovers.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/cable-standing-up-straight-crossovers.gif',
    false,
    NULL
  ),
  (
    'chest_cable_crossover_low',
    'Crossover Polia Baixa',
    'Low Cable Crossover',
    'chest',
    'cable',
    'Peitoral Superior',
    '{"Deltoide Anterior (Clavicular)"}'::text[],
    'Com os cabos no ponto mais baixo, puxe para cima e para o centro até a linha do queixo.',
    'Puxe de baixo para cima convergindo as mãos na altura do peito/queixo com tensão contínua.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/cable-upper-chest-crossovers.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/cable-upper-chest-crossovers.gif',
    false,
    NULL
  ),
  (
    'chest_machine_chest_press',
    'Supino na Máquina (Chest Press)',
    'Machine Chest Press',
    'chest',
    'machine',
    'Peitoral Maior',
    '{"Tríceps","Deltoide Anterior"}'::text[],
    'Ajuste o assento para que as manoplas fiquem na linha do peito. Empurre mantendo os cotovelos ligeiramente abaixo dos ombros.',
    'Ideal para séries de falha e drop sets com total segurança articular na trajetória guiada.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/lever-chest-press.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/lever-chest-press.gif',
    false,
    NULL
  ),
  (
    'chest_pec_deck',
    'Voador / Pec Deck',
    'Pec Deck Machine',
    'chest',
    'machine',
    'Peitoral Maior e Miolo do Peito',
    '{"Deltoide Anterior"}'::text[],
    'Sente com as costas apoiadas. Feche os braços contraindo o peito no centro por 1 segundo antes de abrir devagar.',
    'Ajuste a altura do banco para que os cotovelos fiquem na mesma linha do peitoral médio.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/lever-seated-fly.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/lever-seated-fly.gif',
    false,
    NULL
  ),
  (
    'chest_push_up',
    'Flexão de Braço (Push-Up)',
    'Push-Up',
    'chest',
    'bodyweight',
    'Peitoral, Tríceps e Core',
    '{"Tríceps Braquial","Core","Deltoides"}'::text[],
    'Corpo reto em prancha, mãos na largura dos ombros. Desça até o peito quase tocar o chão e empurre com força.',
    'Não deixe o quadril descer nem a coluna arquear; o corpo deve descer como uma prancha rígida.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/push-up.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/push-up.gif',
    false,
    NULL
  ),
  (
    'back_lat_pulldown_wide',
    'Puxada Frontal Aberta (Pulldown)',
    'Wide-Grip Lat Pulldown',
    'back',
    'cable',
    'Latíssimo do Dorso (Dorsal)',
    '{"Bíceps","Redondo Maior","Rombóides"}'::text[],
    'Segure a barra com pegada pronada aberta. Puxe em direção à parte superior do peito puxando com os cotovelos para baixo.',
    'Inicie o movimento puxando as escápulas para baixo antes de dobrar os cotovelos.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-bar-lateral-pulldown.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-bar-lateral-pulldown.gif',
    false,
    NULL
  ),
  (
    'back_lat_pulldown_close_vbar',
    'Puxada Triângulo / Pegada Fechada',
    'Close-Grip Lat Pulldown',
    'back',
    'cable',
    'Latíssimo do Dorso e Redondo Maior',
    '{"Bíceps Braquial","Braquial","Rombóides"}'::text[],
    'Use o puxador triângulo. Incline o tronco sutilmente para trás e puxe o triângulo até o esterno.',
    'Pegada neutra permite maior amplitude de alongamento dorsal no topo do movimento.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-lateral-pulldown-with-v-bar.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-lateral-pulldown-with-v-bar.gif',
    false,
    NULL
  ),
  (
    'back_barbell_bent_over_row',
    'Remada Curvada com Barra',
    'Bent-Over Barbell Row',
    'back',
    'barbell',
    'Dorsais, Trapézio Médio e Rombóides',
    '{"Bíceps","Trapézio","Eretores da Espinha"}'::text[],
    'Tronco inclinado a 45 graus, coluna neutra. Puxe a barra em direção ao umbigo espremendo as escápulas.',
    'Mantenha a lombar firme e travada em neutro; puxe a barra na direção do umbigo.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/upper-back/barbell-bent-over-row.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/upper-back/barbell-bent-over-row.gif',
    false,
    NULL
  ),
  (
    'back_seated_cable_row',
    'Remada Baixa Sentada (Triângulo)',
    'Seated Cable Row',
    'back',
    'cable',
    'Espessura das Costas e Rombóides',
    '{"Bíceps","Trapézio Médio","Rombóides"}'::text[],
    'Sente-se com as pernas levemente flexionadas. Puxe o triângulo até o abdômen sem jogar o tronco excessivamente para trás.',
    'Mantenha o peito estufado e evite balançar excessivamente o tronco para trás ao puxar.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/upper-back/cable-seated-row.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/upper-back/cable-seated-row.gif',
    false,
    NULL
  ),
  (
    'back_one_arm_dumbbell_row',
    'Remada Unilateral com Halter (Serrote)',
    'One-Arm Dumbbell Row',
    'back',
    'dumbbell',
    'Latíssimo do Dorso',
    '{"Bíceps Braquial","Rombóides"}'::text[],
    'Apoie um joelho e a mão no banco. Com o outro braço, puxe o halter apontando o cotovelo em direção ao quadril.',
    'Puxe com o cotovelo guiando o movimento em direção ao quadril, não em direção ao ombro.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/upper-back/dumbbell-one-arm-bent-over-row.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/upper-back/dumbbell-one-arm-bent-over-row.gif',
    false,
    NULL
  ),
  (
    'back_deadlift',
    'Levantamento Terra (Deadlift)',
    'Barbell Deadlift',
    'back',
    'barbell',
    'Cadeia Posterior, Eretores e Trapézio',
    '{"Glúteos","Isquiotibiais","Trapézio","Core"}'::text[],
    'Barra sobre o meio do pé, quadril posicionado, peito estufado. Puxe estendendo joelhos e quadris simultaneamente.',
    'A barra deve subir rente às canelas e coxas; ative a dorsal como se quisesse quebrar a barra.',
    'advanced',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-deadlift.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-deadlift.gif',
    false,
    NULL
  ),
  (
    'back_pull_up',
    'Barra Fixa (Pull-Up)',
    'Pull-Up',
    'back',
    'bodyweight',
    'Latíssimo do Dorso e Bíceps',
    '{"Bíceps","Redondo Maior","Core"}'::text[],
    'Pegada pronada aberta. Puxe seu próprio corpo até que o queixo ultrapasse a linha da barra.',
    'Puxe até passar o queixo da barra e desça estendendo quase que completamente os braços.',
    'advanced',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/pull-up.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/pull-up.gif',
    false,
    NULL
  ),
  (
    'back_straight_arm_pulldown',
    'Pulldown com Braços Estendidos',
    'Straight-Arm Cable Pulldown',
    'back',
    'cable',
    'Latíssimo do Dorso (Isolamento)',
    '{"Tríceps (Cabeça Longa)","Redondo Maior"}'::text[],
    'Braços quase retos, tronco inclinado 30 graus. Puxe a barra ou corda em arco até encostar nas coxas.',
    'Mantenha os cotovelos fixos com leve flexão para isolar totalmente as grandes dorsais.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-straight-arm-pulldown.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-straight-arm-pulldown.gif',
    false,
    NULL
  ),
  (
    'back_machine_row',
    'Remada Articulada na Máquina',
    'Machine Low Row',
    'back',
    'machine',
    'Costas Geral e Trapézio',
    '{"Bíceps","Trapézio","Rombóides"}'::text[],
    'Ajuste o apoio do peito para total amplitude. Puxe as manoplas com foco em fechar as escápulas.',
    'Apoie o peito na almofada e concentre-se na adução total das escápulas ao final do puxão.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/upper-back/lever-seated-row.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/upper-back/lever-seated-row.gif',
    false,
    NULL
  ),
  (
    'legs_barbell_squat',
    'Agachamento Livre com Barra',
    'Barbell Back Squat',
    'legs',
    'barbell',
    'Quadríceps, Glúteos e Core',
    '{"Glúteo Máximo","Isquiotibiais","Core Lombar"}'::text[],
    'Barra apoiada sobre o trapézio. Desça o quadril abaixo da linha dos joelhos mantendo o peito ereto e empurre pelo calcanhar.',
    'Mantenha os joelhos alinhados com a ponta dos pés e empurre o chão através dos calcanhares.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-full-squat.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-full-squat.gif',
    false,
    NULL
  ),
  (
    'legs_front_squat',
    'Agachamento Frontal',
    'Barbell Front Squat',
    'legs',
    'barbell',
    'Quadríceps e Core Frontal',
    '{"Core Reto","Glúteos"}'::text[],
    'Barra apoiada sobre os deltoides anteriores, cotovelos altos apontados para frente. Agache mantendo a coluna vertical.',
    'Mantenha os cotovelos altos apontados para frente para a barra não rolar dos ombros.',
    'advanced',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-front-squat.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-front-squat.gif',
    false,
    NULL
  ),
  (
    'legs_leg_press_45',
    'Leg Press 45°',
    '45-Degree Leg Press',
    'legs',
    'machine',
    'Quadríceps e Glúteos',
    '{"Glúteos","Isquiotibiais"}'::text[],
    'Pés na largura dos ombros na plataforma. Destrave a máquina e desça até 90 graus sem arredondar a lombar.',
    'Nunca estenda totalmente (trave) os joelhos no topo; mantenha a lombar colada no encosto.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/sled-45-leg-press.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/sled-45-leg-press.gif',
    false,
    NULL
  ),
  (
    'legs_hack_squat',
    'Hack Squat',
    'Hack Squat Machine',
    'legs',
    'machine',
    'Quadríceps',
    '{"Glúteo Máximo"}'::text[],
    'Costas bem apoiadas no encosto. Desça com controle mantendo os pés firmes e empurre na subida.',
    'Excelente estabilização para descer fundo e enfatizar o vasto lateral e reto femoral.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/sled-hack-squat.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/sled-hack-squat.gif',
    false,
    NULL
  ),
  (
    'legs_leg_extension',
    'Cadeira Extensora',
    'Leg Extension',
    'legs',
    'machine',
    'Quadríceps (Isolamento)',
    '{"Reto Femoral"}'::text[],
    'Ajuste a almofada sobre os tornozelos. Estenda as pernas totalmente segurando a contração no topo por 1 segundo.',
    'Segure 1 segundo no ponto de extensão máxima para estresse metabólico nos quadríceps.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/lever-leg-extension.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/lever-leg-extension.gif',
    false,
    NULL
  ),
  (
    'legs_seated_leg_curl',
    'Cadeira Flexora',
    'Seated Leg Curl',
    'legs',
    'machine',
    'Posteriores de Coxa (Isquiotibiais)',
    '{"Gastrocnêmio"}'::text[],
    'Apoio sobre as coxas travado. Flexione as pernas para baixo contraindo os posteriores de coxa com controle.',
    'Mantenha a almofada sobre as coxas bem firme para isolar a flexão dos isquiotibiais.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/hamstrings/lever-seated-leg-curl.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/hamstrings/lever-seated-leg-curl.gif',
    false,
    NULL
  ),
  (
    'legs_lying_leg_curl',
    'Mesa Flexora',
    'Lying Leg Curl',
    'legs',
    'machine',
    'Posteriores de Coxa',
    '{"Glúteos"}'::text[],
    'Deite de bruços no aparelho com o rolete atrás do tendão de Aquiles. Flexione as pernas trazendo os calcanhares em direção aos glúteos.',
    'Evite tirar o quadril do banco durante a flexão das pernas.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/hamstrings/lever-lying-leg-curl.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/hamstrings/lever-lying-leg-curl.gif',
    false,
    NULL
  ),
  (
    'legs_romanian_deadlift',
    'Stiff / Levantamento Romeno (RDL)',
    'Romanian Deadlift (RDL)',
    'legs',
    'barbell',
    'Posteriores de Coxa e Glúteos',
    '{"Glúteos","Eretores da Espinha"}'::text[],
    'Joelhos levemente destravados, empurre o quadril para trás enquanto desce a barra colada nas pernas sentindo o estiramento posterior.',
    'Pense em empurrar o bumbum para a parede de trás com joelhos quase imóveis.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-romanian-deadlift.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-romanian-deadlift.gif',
    false,
    NULL
  ),
  (
    'legs_bulgarian_split_squat',
    'Agachamento Búlgaro',
    'Bulgarian Split Squat',
    'legs',
    'dumbbell',
    'Quadríceps e Glúteos Unilateral',
    '{"Glúteo Médio","Estabilizadores"}'::text[],
    'Apoie um pé atrás em um banco e o outro à frente. Desça o joelho de trás em direção ao solo mantendo o tronco firme.',
    'Mantenha o peso no calcanhar da perna da frente e desça o joelho de trás verticalmente.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/dumbbell-single-leg-split-squat.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/dumbbell-single-leg-split-squat.gif',
    false,
    NULL
  ),
  (
    'legs_walking_lunge',
    'Passada / Avanço com Halteres',
    'Dumbbell Walking Lunge',
    'legs',
    'dumbbell',
    'Pernas Completas e Glúteos',
    '{"Isquiotibiais","Core"}'::text[],
    'Dê passos largos à frente flexionando ambos os joelhos a 90 graus de maneira alternada e fluida.',
    'Dê passos suficientemente longos para manter o joelho da frente a 90° ao tocar o solo.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/walking-lunge.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/walking-lunge.gif',
    false,
    NULL
  ),
  (
    'legs_hip_thrust',
    'Elevação Pélvica com Barra (Hip Thrust)',
    'Barbell Hip Thrust',
    'legs',
    'barbell',
    'Glúteo Máximo',
    '{"Isquiotibiais","Core"}'::text[],
    'Costas apoiadas no banco, barra acolchoada sobre o quadril. Empurre o quadril para cima até alinhar com o tronco e segure.',
    'No topo, contraia o glúteo com força e mantenha o queixo apontando para o peito.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-glute-bridge-two-legs-on-bench-male.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/glutes/barbell-glute-bridge-two-legs-on-bench-male.gif',
    false,
    NULL
  ),
  (
    'legs_hip_abduction_machine',
    'Cadeira Abdutora',
    'Hip Abduction Machine',
    'legs',
    'machine',
    'Glúteo Médio e Mínimo',
    '{"Glúteo Mínimo","Tensor da Fáscia Lata"}'::text[],
    'Abra as pernas contra a resistência da almofada, segurando a contração máxima antes de retornar devagar.',
    'Excelente para estabilidade do quadril e preenchimento lateral dos glúteos.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abductors/lever-seated-hip-abduction.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abductors/lever-seated-hip-abduction.gif',
    false,
    NULL
  ),
  (
    'legs_hip_adduction_machine',
    'Cadeira Adutora',
    'Hip Adduction Machine',
    'legs',
    'machine',
    'Adutores da Coxa',
    '{"Grácil","Pectíneo"}'::text[],
    'Feche as pernas unindo as almofadas no centro, concentrando a força na parte interna da coxa.',
    'Controle a fase excêntrica de abertura para não sofrer estiramento excessivo na virilha.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/adductors/lever-seated-hip-adduction.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/adductors/lever-seated-hip-adduction.gif',
    false,
    NULL
  ),
  (
    'shoulders_overhead_press_barbell',
    'Desenvolvimento Militar com Barra',
    'Overhead Barbell Press',
    'shoulders',
    'barbell',
    'Deltoide Anterior e Lateral',
    '{"Tríceps","Trapézio Superior","Core"}'::text[],
    'Em pé ou sentado, segure a barra na altura do queixo. Empurre reto para cima até estender os braços acima da cabeça.',
    'Mantenha o abdômen e glúteos contraídos para proteger a lombar durante o desenvolvimento.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/barbell-seated-overhead-press.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/barbell-seated-overhead-press.gif',
    false,
    NULL
  ),
  (
    'shoulders_dumbbell_shoulder_press',
    'Desenvolvimento com Halteres',
    'Seated Dumbbell Shoulder Press',
    'shoulders',
    'dumbbell',
    'Deltoides Anterior e Lateral',
    '{"Tríceps Braquial","Trapézio"}'::text[],
    'Sentado com apoio 90 graus, empurre os halteres para cima mantendo os cotovelos levemente à frente do plano coronal.',
    'Não bata os halteres no topo; mantenha os cotovelos levemente anteriorizados.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-seated-shoulder-press.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-seated-shoulder-press.gif',
    false,
    NULL
  ),
  (
    'shoulders_lateral_raise_dumbbell',
    'Elevação Lateral com Halteres',
    'Dumbbell Lateral Raise',
    'shoulders',
    'dumbbell',
    'Deltoide Lateral (Ombro Médio)',
    '{"Trapézio Superior"}'::text[],
    'Com os braços semiflexionados, eleve os halteres lateralmente até a linha dos ombros sem dar tranco com o corpo.',
    'Incline ligeiramente o tronco à frente e erga guiando com os cotovelos, sem balanço.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-lateral-raise.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-lateral-raise.gif',
    false,
    NULL
  ),
  (
    'shoulders_lateral_raise_cable',
    'Elevação Lateral na Polia',
    'Cable Lateral Raise',
    'shoulders',
    'cable',
    'Deltoide Lateral (Tensão Contínua)',
    '{"Manguito Rotador"}'::text[],
    'Passe o cabo por trás ou pela frente do corpo e eleve a manopla lateralmente sentindo tensão constante em todo o arco.',
    'A polia garante resistência contínua até o início do arco, maximizando hipertrofia lateral.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/cable-lateral-raise.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/cable-lateral-raise.gif',
    false,
    NULL
  ),
  (
    'shoulders_front_raise_dumbbell',
    'Elevação Frontal com Halteres',
    'Dumbbell Front Raise',
    'shoulders',
    'dumbbell',
    'Deltoide Anterior',
    '{"Peitoral Superior"}'::text[],
    'Eleve os halteres à frente do corpo até a linha dos olhos, mantendo o abdômen contraído.',
    'Erga até a linha dos olhos com pegada pronada ou neutra de forma estritamente controlada.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-front-raise.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-front-raise.gif',
    false,
    NULL
  ),
  (
    'shoulders_reverse_fly_machine',
    'Crucifixo Inverso / Peck Deck Invertido',
    'Reverse Pec Deck Fly',
    'shoulders',
    'machine',
    'Deltoide Posterior',
    '{"Rombóides","Trapézio Médio"}'::text[],
    'Sente de frente para o aparelho. Abra os braços para trás contraindo a porção posterior dos ombros.',
    'Foque em abrir com a força da parte posterior do ombro sem dar impulso com o tronco.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/lever-seated-reverse-fly.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/lever-seated-reverse-fly.gif',
    false,
    NULL
  ),
  (
    'shoulders_face_pull',
    'Face Pull na Polia',
    'Cable Face Pull',
    'shoulders',
    'cable',
    'Deltoide Posterior, Manguito e Trapézio',
    '{"Manguito Rotador","Trapézio Médio e Superior"}'::text[],
    'Polia na altura do rosto com corda. Puxe separando as pontas em direção às orelhas e rodando os ombros externamente.',
    'Puxe a corda em direção aos olhos/orelhas fazendo rotação externa dos polegares para trás.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/cable-standing-rear-delt-row-with-rope.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/cable-standing-rear-delt-row-with-rope.gif',
    false,
    NULL
  ),
  (
    'shoulders_dumbbell_shrug',
    'Encolhimento com Halteres (Trapézio)',
    'Dumbbell Shrug',
    'shoulders',
    'dumbbell',
    'Trapézio Superior',
    '{"Levantador da Escápula","Antebraço"}'::text[],
    'Com halteres ao lado do corpo, eleve os ombros em direção às orelhas sem rodá-los. Segure no topo por 1 segundo.',
    'Suba em linha reta em direção às orelhas; nunca faça giros ou rotações circulares com os ombros.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/traps/dumbbell-shrug.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/traps/dumbbell-shrug.gif',
    false,
    NULL
  ),
  (
    'biceps_barbell_curl',
    'Rosca Direta com Barra',
    'Barbell Bicep Curl',
    'biceps',
    'barbell',
    'Bíceps Braquial',
    '{"Braquial","Antebraço"}'::text[],
    'Cotovelos colados ao tronco. Flexione os braços trazendo a barra ao peito sem balançar o corpo.',
    'Mantenha os cotovelos fixados ao lado do corpo e evite usar o impulso da coluna.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/barbell-curl.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/barbell-curl.gif',
    false,
    NULL
  ),
  (
    'biceps_ez_bar_curl',
    'Rosca Direta com Barra W',
    'EZ-Bar Curl',
    'biceps',
    'barbell',
    'Bíceps Braquial e Braquiorradial',
    '{"Braquiorradial","Braquial"}'::text[],
    'Pegada semi-supinada na curvatura da barra W para conforto das articulações do punho.',
    'A barra W reduz o torque e alivia a pressão na articulação dos punhos.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/ez-barbell-curl.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/ez-barbell-curl.gif',
    false,
    NULL
  ),
  (
    'biceps_dumbbell_curl_alternating',
    'Rosca Alternada com Halteres',
    'Alternating Dumbbell Curl',
    'biceps',
    'dumbbell',
    'Bíceps Braquial com Supinação',
    '{"Braquial","Antebraço"}'::text[],
    'Suba um halter por vez, girando o punho para fora (supinação) no topo do movimento.',
    'Inicie com pegada neutra e supine o punho (palma virada para cima) a partir do meio da subida.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-biceps-curl.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-biceps-curl.gif',
    false,
    NULL
  ),
  (
    'biceps_hammer_curl',
    'Rosca Martelo com Halteres',
    'Hammer Curl',
    'biceps',
    'dumbbell',
    'Braquial e Braquiorradial (Antebraço)',
    '{"Braquiorradial","Braquial"}'::text[],
    'Pegada neutra (palmas viradas uma para a outra). Flexione os antebraços mantendo a pegada firme.',
    'Pegada neutra o tempo todo. Excelente para aumentar a densidade e largura do braço.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-hammer-curl.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-hammer-curl.gif',
    false,
    NULL
  ),
  (
    'biceps_incline_dumbbell_curl',
    'Rosca Inclinada no Banco 45°',
    'Incline Dumbbell Curl',
    'biceps',
    'dumbbell',
    'Cabeça Longa do Bíceps (Pico)',
    '{"Braquial"}'::text[],
    'Deite-se no banco a 45 graus com os braços pendurados para trás. Flexione aproveitando o grande alongamento inicial.',
    'Banco a 45°. O estiramento inicial da cabeça longa proporciona estímulo hipertrófico diferenciado.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-incline-biceps-curl.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-incline-biceps-curl.gif',
    false,
    NULL
  ),
  (
    'biceps_scott_curl',
    'Rosca Scott (Banco Scott)',
    'Preacher Curl',
    'biceps',
    'barbell',
    'Bíceps (Isolamento Cabeça Curta)',
    '{"Braquial"}'::text[],
    'Braços repousados na almofada inclinada. Flexione até o topo sem desencostar os tríceps do apoio.',
    'Apoie completamente os tríceps na almofada para impossibilitar o uso de impulso corporal.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/barbell-preacher-curl.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/barbell-preacher-curl.gif',
    false,
    NULL
  ),
  (
    'biceps_concentration_curl',
    'Rosca Concentrada',
    'Concentration Curl',
    'biceps',
    'dumbbell',
    'Pico do Bíceps',
    '{"Braquiorradial"}'::text[],
    'Sentado, apoie o cotovelo na face interna da coxa e flexione o halter de forma isolada.',
    'Apoie o cotovelo na parte interna da coxa e sinta o pico de contração do bíceps.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-concentration-curl.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-concentration-curl.gif',
    false,
    NULL
  ),
  (
    'biceps_cable_curl',
    'Rosca na Polia Baixa',
    'Standing Cable Curl',
    'biceps',
    'cable',
    'Bíceps com Tensão Contínua',
    '{"Braquial"}'::text[],
    'Puxe a barra reta ou barra W conectada à polia baixa mantendo tensão constante durante toda a subida e descida.',
    'Tensão constante em todas as fases da repetição, ideal para séries até a exaustão.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/cable-curl.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/cable-curl.gif',
    false,
    NULL
  ),
  (
    'triceps_rope_pushdown',
    'Tríceps Corda na Polia',
    'Cable Rope Triceps Pushdown',
    'triceps',
    'cable',
    'Tríceps (Cabeça Lateral e Medial)',
    '{"Ancôneo"}'::text[],
    'Empurre a corda para baixo abrindo as pontas no final do movimento para contração máxima.',
    'Abra as pontas da corda na base do movimento para contração máxima da cabeça lateral.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/cable-pushdown-with-rope-attachment.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/cable-pushdown-with-rope-attachment.gif',
    false,
    NULL
  ),
  (
    'triceps_straight_bar_pushdown',
    'Tríceps Pulley com Barra Reta/V',
    'Cable Bar Triceps Pushdown',
    'triceps',
    'cable',
    'Tríceps Braquial',
    '{"Ancôneo"}'::text[],
    'Cotovelos junto às costelas. Empurre a barra até estender completamente os braços.',
    'Mantenha os cotovelos colados ao tronco e empurre estendendo totalmente os braços.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/cable-triceps-pushdown-v-bar.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/cable-triceps-pushdown-v-bar.gif',
    false,
    NULL
  ),
  (
    'triceps_skull_crusher',
    'Tríceps Testa com Barra W',
    'Lying Triceps Extension (Skull Crusher)',
    'triceps',
    'barbell',
    'Cabeça Longa do Tríceps',
    '{"Cabeça Medial e Lateral"}'::text[],
    'Deitado no banco reto, flexione os cotovelos descendo a barra até a testa e estenda novamente.',
    'Incline os braços ligeiramente para trás da cabeça para manter tensão constante no topo.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/barbell-lying-triceps-extension-skull-crusher.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/barbell-lying-triceps-extension-skull-crusher.gif',
    false,
    NULL
  ),
  (
    'triceps_overhead_cable_extension',
    'Tríceps Francês na Polia (Corda)',
    'Overhead Cable Triceps Extension',
    'triceps',
    'cable',
    'Cabeça Longa do Tríceps (Alongamento)',
    '{"Ancôneo"}'::text[],
    'De costas para a polia, incline o corpo à frente e estenda a corda para a diagonal superior mantendo cotovelos firmes.',
    'Enfatiza a cabeça longa do tríceps em posição alongada; mantenha cotovelos fechados.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/cable-overhead-triceps-extension-rope-attachment.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/cable-overhead-triceps-extension-rope-attachment.gif',
    false,
    NULL
  ),
  (
    'triceps_overhead_dumbbell_extension',
    'Tríceps Francês com Halter',
    'Overhead Dumbbell Triceps Extension',
    'triceps',
    'dumbbell',
    'Cabeça Longa do Tríceps',
    '{"Cabeça Lateral"}'::text[],
    'Segure um halter com ambas as mãos atrás da cabeça e estenda verticalmente.',
    'Segure a anilha superior do halter com as duas mãos e desça profundamente atrás da cabeça.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/dumbbell-seated-triceps-extension.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/dumbbell-seated-triceps-extension.gif',
    false,
    NULL
  ),
  (
    'triceps_dips_parallel_bars',
    'Paralelas para Tríceps (Dips)',
    'Triceps Dips',
    'triceps',
    'bodyweight',
    'Tríceps e Peitoral Inferior',
    '{"Peitoral Inferior","Deltoide Anterior"}'::text[],
    'Nas barras paralelas com tronco mais ereto, desça até 90 graus nos cotovelos e empurre com os braços.',
    'Mantenha o tronco mais ereto e os cotovelos apontados para trás para focar no tríceps.',
    'advanced',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/triceps-dip.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/triceps-dip.gif',
    false,
    NULL
  ),
  (
    'triceps_bench_dips',
    'Tríceps no Banco (Mergulho)',
    'Bench Dips',
    'triceps',
    'bodyweight',
    'Tríceps Braquial',
    '{"Deltoide Anterior"}'::text[],
    'Mãos apoiadas na borda do banco e pés à frente. Desça o quadril próximo ao banco flexionando os cotovelos.',
    'Mantenha as costas rente ao banco durante a descida para poupar a articulação dos ombros.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/weighted-three-bench-dips.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/weighted-three-bench-dips.gif',
    false,
    NULL
  ),
  (
    'triceps_kickback_cable',
    'Tríceps Coice na Polia ou Halter',
    'Triceps Kickback',
    'triceps',
    'cable',
    'Tríceps (Contração de Pico)',
    '{"Ancôneo"}'::text[],
    'Tronco paralelo ao chão, cotovelo alto fixo. Estenda o antebraço para trás e esprema o tríceps.',
    'Mantenha o braço estático paralelo ao chão e movimente apenas o antebraço contraindo no final.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/cable-kickback.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/cable-kickback.gif',
    false,
    NULL
  ),
  (
    'calves_standing_raise_machine',
    'Panturrilha em Pé na Máquina',
    'Standing Calf Raise',
    'calves',
    'machine',
    'Gastrocnêmio',
    '{"Sóleo"}'::text[],
    'Com a ponta dos pés no degrau, desça para o alongamento total e suba na ponta dos pés segurando 1s no topo.',
    'Faça uma pausa de 1 segundo no alongamento inferior e outra pausa de 1 segundo na contração máxima.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/calves/lever-standing-calf-raise.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/calves/lever-standing-calf-raise.gif',
    false,
    NULL
  ),
  (
    'calves_seated_raise_machine',
    'Gêmeos / Panturrilha Sentado',
    'Seated Calf Raise',
    'calves',
    'machine',
    'Sóleo',
    '{"Tibial Posterior"}'::text[],
    'Com as pernas dobradas a 90 graus sob as almofadas, flexione os tornozelos com amplitude completa.',
    'Com os joelhos flexionados a 90°, o músculo sóleo assume quase todo o trabalho mecânico.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/calves/lever-seated-calf-raise.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/calves/lever-seated-calf-raise.gif',
    false,
    NULL
  ),
  (
    'calves_leg_press_raise',
    'Panturrilha no Leg Press',
    'Leg Press Calf Press',
    'calves',
    'machine',
    'Gastrocnêmio e Sóleo',
    '{"Sóleo"}'::text[],
    'Apoie a ponta dos pés na borda inferior da plataforma do Leg Press e empurre estendendo os tornozelos.',
    'Trave os joelhos com leve flexão de segurança e trabalhe exclusivamente a flexão plantar dos tornozelos.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/calves/sled-45-calf-press.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/calves/sled-45-calf-press.gif',
    false,
    NULL
  ),
  (
    'abs_crunch_floor',
    'Abdominal Tradicional (Crunch)',
    'Floor Crunch',
    'abs',
    'bodyweight',
    'Reto Abdominal',
    '{"Oblíquos"}'::text[],
    'Deitado no colchonete, flexione a coluna enrolando o abdômen sem puxar o pescoço.',
    'Foque em aproximar a caixa torácica da pelve soltando o ar no final da contração.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/crunch-floor.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/crunch-floor.gif',
    false,
    NULL
  ),
  (
    'abs_hanging_leg_raise',
    'Elevação de Pernas na Barra Fixa',
    'Hanging Leg Raise',
    'abs',
    'bodyweight',
    'Reto Abdominal Inferior e Flexores',
    '{"Flexores do Quadril","Antebraço"}'::text[],
    'Pendurado na barra fixa, eleve os joelhos ou pernas retas até a altura do quadril enrolando a pelve.',
    'Enrole a bacia para frente ao subir os joelhos ou pernas em vez de só levantar as coxas.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/hanging-leg-raise.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/hanging-leg-raise.gif',
    false,
    NULL
  ),
  (
    'abs_plank',
    'Prancha Isométrica',
    'Plank',
    'abs',
    'bodyweight',
    'Core Geral, Transverso e Lombar',
    '{"Transverso Abdominal","Glúteos","Lombar"}'::text[],
    'Apoie antebraços e pontas dos pés no chão. Mantenha o corpo reto e o abdômen rígido pelo tempo determinado.',
    'Ative glúteos e abdômen simultaneamente sem permitir que a bacia caia ou suba demais.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/weighted-front-plank.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/weighted-front-plank.gif',
    false,
    NULL
  ),
  (
    'abs_cable_crunch',
    'Abdominal na Polia Alta (Cable Crunch)',
    'Kneeling Cable Crunch',
    'abs',
    'cable',
    'Reto Abdominal com Carga',
    '{"Oblíquos"}'::text[],
    'De joelhos segurando a corda atrás da cabeça, enrole a coluna levando os cotovelos em direção aos joelhos.',
    'Mantenha a distância entre quadril e calcanhares fixa; flexione apenas a coluna lombar e torácica.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/cable-kneeling-crunch.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/cable-kneeling-crunch.gif',
    false,
    NULL
  ),
  (
    'abs_wheel_rollout',
    'Roda Abdominal (Ab Wheel)',
    'Ab Wheel Rollout',
    'abs',
    'other',
    'Core Completo e Anti-extensão',
    '{"Dorsais","Tríceps","Lombar"}'::text[],
    'De joelhos, empurre a roda para frente mantendo o abdômen firme sem deixar a lombar arquear, e retorne.',
    'Excelente trabalho anti-extensão; vá apenas até onde conseguir manter a coluna em neutro.',
    'advanced',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/wheel-rollerout.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/wheel-rollerout.gif',
    false,
    NULL
  ),
  (
    'abs_russian_twist',
    'Russian Twist',
    'Russian Twist',
    'abs',
    'dumbbell',
    'Oblíquos e Core Rotacional',
    '{"Reto Abdominal","Flexores do Quadril"}'::text[],
    'Sentado com os pés elevados, rotacione o tronco de um lado para o outro controladamente segurando um halter ou anilha.',
    'Rotacione os ombros e a caixa torácica de um lado a outro, não apenas os braços.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/russian-twist.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/russian-twist.gif',
    false,
    NULL
  ),
  (
    'cardio_treadmill_running',
    'Corrida na Esteira',
    'Treadmill Running',
    'cardio',
    'machine',
    'Sistema Cardiovascular e Membros Inferiores',
    '{"Quadríceps","Glúteos","Panturrilhas"}'::text[],
    'Corrida com ritmo constante ou intervalado na esteira para queima calórica e condicionamento.',
    'Mantenha a postura ereta e a passada cadenciada com aterrissagem sobre o médio pé.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/run.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/run.gif',
    false,
    NULL
  ),
  (
    'cardio_incline_treadmill_walk',
    'Caminhada Inclinada na Esteira',
    'Incline Treadmill Walk',
    'cardio',
    'machine',
    'Glúteos, Panturrilhas e Cardiovascular',
    '{"Glúteos","Panturrilhas"}'::text[],
    'Velocidade moderada (4.5 a 6 km/h) com inclinação entre 8% e 15% para queima de gordura de baixo impacto.',
    'Não segure nos apoios da esteira para preservar o recrutamento muscular e gasto calórico real.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/walking-on-incline-treadmill.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/walking-on-incline-treadmill.gif',
    false,
    NULL
  ),
  (
    'cardio_stationary_bike',
    'Bicicleta Ergométrica',
    'Stationary Cycling',
    'cardio',
    'machine',
    'Cardiovascular e Quadríceps',
    '{"Quadríceps","Isquiotibiais"}'::text[],
    'Pedal moderado a intenso mantendo cadência entre 70 e 90 RPM com resistência ajustada.',
    'Ajuste a altura do banco para que o joelho mantenha uma leve flexão no ponto mais baixo do pedal.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/stationary-bike-walk.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/stationary-bike-walk.gif',
    false,
    NULL
  ),
  (
    'cardio_elliptical',
    'Elíptico',
    'Elliptical Trainer',
    'cardio',
    'machine',
    'Cardiovascular de Baixo Impacto',
    '{"Braços","Pernas Inteiras"}'::text[],
    'Movimento contínuo sincronizado de braços e pernas suave para as articulações.',
    'Ideal para treinos aeróbicos com impacto mínimo nas articulações dos joelhos e tornozelos.',
    'beginner',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/walk-elliptical-cross-trainer.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/walk-elliptical-cross-trainer.gif',
    false,
    NULL
  ),
  (
    'cardio_stairmaster',
    'Simulador de Escada',
    'StairMaster / StepMill',
    'cardio',
    'machine',
    'Glúteos, Pernas e Resistência Cardíaca',
    '{"Glúteo Máximo","Quadríceps","Panturrilhas"}'::text[],
    'Suba os degraus sem apoiar todo o peso do corpo nos corrimãos, mantendo postura ereta.',
    'Suba apoiando a planta inteira do pé em cada degrau para ativação ótima de glúteos.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/walking-on-stepmill.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/walking-on-stepmill.gif',
    false,
    NULL
  ),
  (
    'cardio_jump_rope',
    'Pular Corda',
    'Jump Rope',
    'cardio',
    'other',
    'Panturrilhas, Coordenação e Cardio',
    '{"Panturrilhas","Ombros","Coordenação"}'::text[],
    'Saltos curtos com a ponta dos pés impulsionados pelos punhos de forma ritmada.',
    'Dê pequenos saltos de apenas 2 a 3 cm do chão rodando a corda apenas pelos punhos.',
    'intermediate',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/jump-rope.gif',
    'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/cardio/jump-rope.gif',
    false,
    NULL
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  category = EXCLUDED.category,
  equipment = EXCLUDED.equipment,
  target_muscle = EXCLUDED.target_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  instructions = EXCLUDED.instructions,
  tips = EXCLUDED.tips,
  difficulty = EXCLUDED.difficulty,
  gif_url = EXCLUDED.gif_url,
  thumbnail_url = EXCLUDED.thumbnail_url,
  updated_at = timezone('utc'::text, now());
